RegistrationController:
addUser_correctUser
> POST /api/v1/students/registration HTTP/1.1
> Host: localhost:8080
> Content-Type: application/json
> User-Agent: insomnia/11.1.0
> Accept: */*
> Content-Length: 183

| {
| 	"firstName" : "Alex",
| 	"lastName" : "Ivanov",
| 	"patronymic" : "Ivanovich",
| 	"birthDate" : "1990-06-22",
| 	"email" : "alex@mail.ru",
| 	"password" : "123",
| 	"passwordConfirm" : "123"
| }

* Mark bundle as not supporting multiuse

< HTTP/1.1 200
< Vary: Origin
< Vary: Access-Control-Request-Method
< Vary: Access-Control-Request-Headers
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 0
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< Pragma: no-cache
< Expires: 0
< X-Frame-Options: DENY
< Content-Type: application/json
< Transfer-Encoding: chunked
< Date: Sun, 22 Jun 2025 15:28:44 GMT
< {
< 	"id": 6,
< 	"patronymic": "Ivanovich",
< 	"email": "alex@mail.ru",
< 	"reviews": [],
< 	"firstName": "Alex",
< 	"lastName": "Ivanov",
< 	"birthDate": "1990-06-22",
< 	"coursesNames": []
< }

addUser_wrongConfirmPassword
> POST /api/v1/students/registration HTTP/1.1
> Host: localhost:8080
> Content-Type: application/json
> User-Agent: insomnia/11.1.0
> Accept: */*
> Content-Length: 184

| {
| 	"firstName" : "Alex",
| 	"lastName" : "Ivanov",
| 	"patronymic" : "Ivanovich",
| 	"birthDate" : "1990-06-22",
| 	"email" : "alex@mail.ru",
| 	"password" : "123",
| 	"passwordConfirm" : "1234"
| }

* Mark bundle as not supporting multiuse

< HTTP/1.1 400
< Vary: Origin
< Vary: Access-Control-Request-Method
< Vary: Access-Control-Request-Headers
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 0
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< Pragma: no-cache
< Expires: 0
< X-Frame-Options: DENY
< Content-Length: 0
< Date: Sun, 22 Jun 2025 17:02:02 GMT
< Connection: close

LkController:
getStudent_existingStudent
> GET /api/v1/students/lk/6 HTTP/1.1
> Host: localhost:8080
> Content-Type: application/json
> User-Agent: insomnia/11.1.0
> Authorization: Basic YWxleEBtYWlsLnJ1OjEyMw==
> Accept: */*
> Content-Length: 183

| {
| 	"firstName" : "Alex",
| 	"lastName" : "Ivanov",
| 	"patronymic" : "Ivanovich",
| 	"birthDate" : "1990-06-22",
| 	"email" : "alex@mail.ru",
| 	"password" : "123",
| 	"passwordConfirm" : "123"
| }

* Mark bundle as not supporting multiuse

< HTTP/1.1 200
< Vary: Origin
< Vary: Access-Control-Request-Method
< Vary: Access-Control-Request-Headers
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 0
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< Pragma: no-cache
< Expires: 0
< X-Frame-Options: DENY
< Content-Type: application/json
< Transfer-Encoding: chunked
< Date: Sun, 22 Jun 2025 15:32:31 GMT
< {
< 	"id": 6,
< 	"patronymic": "Ivanovich",
< 	"email": "alex@mail.ru",
< 	"reviews": [],
< 	"firstName": "Alex",
< 	"lastName": "Ivanov",
< 	"birthDate": "1990-06-22",
< 	"coursesNames": []
< }

getStudent_notExistingStudent
> GET /api/v1/students/lk/6 HTTP/1.1
> Host: localhost:8080
> User-Agent: insomnia/11.1.0
> Authorization: Basic dXNlcjE6MTIzNDU=
> Accept: */*

* Mark bundle as not supporting multiuse

< HTTP/1.1 401
< Vary: Origin
< Vary: Access-Control-Request-Method
< Vary: Access-Control-Request-Headers
< WWW-Authenticate: Basic realm="Realm"
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 0
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< Pragma: no-cache
< Expires: 0
< X-Frame-Options: DENY
< Content-Type: application/json
< Transfer-Encoding: chunked
< Date: Sun, 22 Jun 2025 16:59:59 GMT

StudentController:
updateStudent_existingStudent
> PUT /api/v1/students HTTP/1.1
> Host: localhost:8080
> Content-Type: application/json
> User-Agent: insomnia/11.1.0
> Accept: */*
> Content-Length: 193

| {
| 	"id": 6,
| 	"firstName" : "Alex",
| 	"lastName" : "Petrov",
| 	"patronymic" : "Ivanovich",
| 	"birthDate" : "1990-06-22",
| 	"email" : "alex@mail.ru",
| 	"password" : "123",
| 	"passwordConfirm" : "123"
| }

* Mark bundle as not supporting multiuse

< HTTP/1.1 201
< Vary: Origin
< Vary: Access-Control-Request-Method
< Vary: Access-Control-Request-Headers
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 0
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< Pragma: no-cache
< Expires: 0
< X-Frame-Options: DENY
< Content-Type: application/json
< Transfer-Encoding: chunked
< Date: Sun, 22 Jun 2025 15:45:07 GMT
< {
< 	"id": 6,
< 	"patronymic": "Ivanovich",
< 	"email": "alex@mail.ru",
< 	"reviews": [],
< 	"firstName": "Alex",
< 	"lastName": "Petrov",
< 	"birthDate": "1990-06-22",
< 	"coursesNames": []
< }

updateStudent_notExistingStudent
> PUT /api/v1/students HTTP/1.1
> Host: localhost:8080
> Content-Type: application/json
> User-Agent: insomnia/11.1.0
> Accept: */*
> Content-Length: 193

| {
| 	"id": 6,
| 	"firstName" : "Alex",
| 	"lastName" : "Petrov",
| 	"patronymic" : "Ivanovich",
| 	"birthDate" : "1990-06-22",
| 	"email" : "alex@mail.ru",
| 	"password" : "123",
| 	"passwordConfirm" : "123"
| }

* Mark bundle as not supporting multiuse

< HTTP/1.1 404
< Vary: Origin
< Vary: Access-Control-Request-Method
< Vary: Access-Control-Request-Headers
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 0
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< Pragma: no-cache
< Expires: 0
< X-Frame-Options: DENY
< Content-Length: 0
< Date: Sun, 22 Jun 2025 16:55:24 GMT

deleteStudent_existingStudent
> DELETE /api/v1/students/6 HTTP/1.1
> Host: localhost:8080
> User-Agent: insomnia/11.1.0
> Accept: */*

* Mark bundle as not supporting multiuse

< HTTP/1.1 200
< Vary: Origin
< Vary: Access-Control-Request-Method
< Vary: Access-Control-Request-Headers
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 0
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< Pragma: no-cache
< Expires: 0
< X-Frame-Options: DENY
< Content-Type: application/json
< Transfer-Encoding: chunked
< Date: Sun, 22 Jun 2025 15:47:21 GMT
< {
< 	"id": 6,
< 	"patronymic": "Ivanovich",
< 	"email": "alex@mail.ru",
< 	"reviews": [],
< 	"firstName": "Alex",
< 	"lastName": "Petrov",
< 	"birthDate": "1990-06-22",
< 	"coursesNames": []
< }

deleteStudent_notExistingStudent
> DELETE /api/v1/students/6 HTTP/1.1
> Host: localhost:8080
> User-Agent: insomnia/11.1.0
> Accept: */*

* Mark bundle as not supporting multiuse

< HTTP/1.1 404
< Vary: Origin
< Vary: Access-Control-Request-Method
< Vary: Access-Control-Request-Headers
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 0
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< Pragma: no-cache
< Expires: 0
< X-Frame-Options: DENY
< Content-Length: 0
< Date: Sun, 22 Jun 2025 16:52:37 GMT

signUpCourse_existingCourse
> POST /api/v1/students/4/courses/signup/Python HTTP/1.1
> Host: localhost:8080
> User-Agent: insomnia/11.1.0
> Accept: */*
> Content-Length: 0

* Mark bundle as not supporting multiuse

< HTTP/1.1 200
< Vary: Origin
< Vary: Access-Control-Request-Method
< Vary: Access-Control-Request-Headers
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 0
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< Pragma: no-cache
< Expires: 0
< X-Frame-Options: DENY
< Content-Type: application/json
< Transfer-Encoding: chunked
< Date: Sun, 22 Jun 2025 16:51:20 GMT
< {
< 	"id": 4,
< 	"patronymic": null,
< 	"email": "s_sergeev@mail.ru",
< 	"reviews": [],
< 	"firstName": "Sergey",
< 	"lastName": "Sergeev",
< 	"birthDate": "2000-10-10",
< 	"coursesNames": [
< 		"Python"
< 	]
< }

signUpCourse_notExistingCourse
> POST /api/v1/students/4/courses/signup/Scala HTTP/1.1
> Host: localhost:8080
> User-Agent: insomnia/11.1.0
> Accept: */*
> Content-Length: 0

* Mark bundle as not supporting multiuse

< HTTP/1.1 400
< Vary: Origin
< Vary: Access-Control-Request-Method
< Vary: Access-Control-Request-Headers
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 0
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< Pragma: no-cache
< Expires: 0
< X-Frame-Options: DENY
< Content-Length: 0
< Date: Sun, 22 Jun 2025 16:49:53 GMT
< Connection: close

leaveReview_signedUpCourse
> POST /api/v1/students/6/courses/leave-review/JavaEE HTTP/1.1
> Host: localhost:8080
> Content-Type: application/json
> User-Agent: insomnia/11.1.0
> Accept: */*
> Content-Length: 29

| {
| 	"review": "Good course!"
| }

* Mark bundle as not supporting multiuse

< HTTP/1.1 200
< Vary: Origin
< Vary: Access-Control-Request-Method
< Vary: Access-Control-Request-Headers
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 0
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< Pragma: no-cache
< Expires: 0
< X-Frame-Options: DENY
< Content-Type: application/json
< Transfer-Encoding: chunked
< Date: Sun, 22 Jun 2025 17:11:38 GMT
< {
< 	"id": 6,
< 	"patronymic": "Ivanovich",
< 	"email": "alex@mail.ru",
< 	"reviews": [
< 		{
< 			"text": "{\n\t\"review\": \"Good course!\"\n}",
< 			"courseName": "Python"
< 		},
< 		{
< 			"text": "{\n\t\"review\": \"Good course!\"\n}",
< 			"courseName": "JavaEE"
< 		}
< 	],
< 	"firstName": "Alex",
< 	"lastName": "Ivanov",
< 	"birthDate": "1990-06-22",
< 	"coursesNames": [
< 		"JavaEE",
< 		"Python"
< 	]
< }

leaveReview_notSignedUpCourse
> POST /api/v1/students/6/courses/leave-review/Scala HTTP/1.1
> Host: localhost:8080
> Content-Type: application/json
> User-Agent: insomnia/11.1.0
> Accept: */*
> Content-Length: 29

| {
| 	"review": "Good course!"
| }

* Mark bundle as not supporting multiuse

< HTTP/1.1 400
< Vary: Origin
< Vary: Access-Control-Request-Method
< Vary: Access-Control-Request-Headers
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 0
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< Pragma: no-cache
< Expires: 0
< X-Frame-Options: DENY
< Content-Length: 0
< Date: Sun, 22 Jun 2025 17:10:33 GMT
< Connection: close

getStudentsOnCourse_existingCourse
> GET /api/v1/students/on-course=Python HTTP/1.1
> Host: localhost:8080
> User-Agent: insomnia/11.1.0
> Accept: */*

* Mark bundle as not supporting multiuse

< HTTP/1.1 200
< Vary: Origin
< Vary: Access-Control-Request-Method
< Vary: Access-Control-Request-Headers
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 0
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< Pragma: no-cache
< Expires: 0
< X-Frame-Options: DENY
< Content-Type: application/json
< Transfer-Encoding: chunked
< Date: Sun, 22 Jun 2025 17:13:25 GMT
< [
< 	{
< 		"id": 4,
< 		"patronymic": null,
< 		"email": "s_sergeev@mail.ru",
< 		"reviews": [],
< 		"firstName": "Sergey",
< 		"lastName": "Sergeev",
< 		"birthDate": "2000-10-10",
< 		"coursesNames": [
< 			"JavaEE",
< 			"Python"
< 		]
< 	},
< 	{
< 		"id": 5,
< 		"patronymic": null,
< 		"email": "u_gagarin@mail.ru",
< 		"reviews": [],
< 		"firstName": "Uriy",
< 		"lastName": "Gagarin",
< 		"birthDate": "2011-11-11",
< 		"coursesNames": [
< 			"Python"
< 		]
< 	},
< 	{
< 		"id": 6,
< 		"patronymic": "Ivanovich",
< 		"email": "alex@mail.ru",
< 		"reviews": [
< 			{
< 				"text": "{\n\t\"review\": \"Good course!\"\n}",
< 				"courseName": "Python"
< 			},
< 			{
< 				"text": "{\n\t\"review\": \"Good course!\"\n}",
< 				"courseName": "JavaEE"
< 			}
< 		],
< 		"firstName": "Alex",
< 		"lastName": "Ivanov",
< 		"birthDate": "1990-06-22",
< 		"coursesNames": [
< 			"JavaEE",
< 			"Python"
< 		]
< 	}
< ]

getStudentsOnCourse_notExistingCourse
> GET /api/v1/students/on-course=Scala HTTP/1.1
> Host: localhost:8080
> User-Agent: insomnia/11.1.0
> Accept: */*

* Mark bundle as not supporting multiuse

< HTTP/1.1 400
< Vary: Origin
< Vary: Access-Control-Request-Method
< Vary: Access-Control-Request-Headers
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 0
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< Pragma: no-cache
< Expires: 0
< X-Frame-Options: DENY
< Content-Length: 0
< Date: Sun, 22 Jun 2025 17:15:39 GMT
< Connection: close

getStudentsOlderThan20
> GET /api/v1/students/older-than=20 HTTP/1.1
> Host: localhost:8080
> User-Agent: insomnia/11.1.0
> Accept: */*

* Mark bundle as not supporting multiuse

< HTTP/1.1 200
< Vary: Origin
< Vary: Access-Control-Request-Method
< Vary: Access-Control-Request-Headers
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 0
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< Pragma: no-cache
< Expires: 0
< X-Frame-Options: DENY
< Content-Type: application/json
< Transfer-Encoding: chunked
< Date: Sun, 22 Jun 2025 17:16:48 GMT
[
	{
		"id": 1,
		"patronymic": "Victorovich",
		"email": "AVFaletyonok@yandex.ru",
		"reviews": [],
		"firstName": "Alexander",
		"lastName": "Faletyonok",
		"birthDate": "1980-02-21",
		"coursesNames": []
	},
	{
		"id": 2,
		"patronymic": null,
		"email": "p_first@mail.ru",
		"reviews": [],
		"firstName": "Peter",
		"lastName": "TheFirst",
		"birthDate": "1990-03-03",
		"coursesNames": []
	},
	{
		"id": 3,
		"patronymic": null,
		"email": "o_ivanov@mail.ru",
		"reviews": [],
		"firstName": "Oleg",
		"lastName": "Ivanov",
		"birthDate": "1999-09-09",
		"coursesNames": []
	},
	{
		"id": 4,
		"patronymic": null,
		"email": "s_sergeev@mail.ru",
		"reviews": [],
		"firstName": "Sergey",
		"lastName": "Sergeev",
		"birthDate": "2000-10-10",
		"coursesNames": [
			"JavaEE",
			"Python"
		]
	},
	{
		"id": 6,
		"patronymic": "Ivanovich",
		"email": "alex@mail.ru",
		"reviews": [
			{
				"text": "{\n\t\"review\": \"Good course!\"\n}",
				"courseName": "Python"
			},
			{
				"text": "{\n\t\"review\": \"Good course!\"\n}",
				"courseName": "JavaEE"
			}
		],
		"firstName": "Alex",
		"lastName": "Ivanov",
		"birthDate": "1990-06-22",
		"coursesNames": [
			"JavaEE",
			"Python"
		]
	}
]

getStudentsOlderThan150
> GET /api/v1/students/older-than=150 HTTP/1.1
> Host: localhost:8080
> User-Agent: insomnia/11.1.0
> Accept: */*

* Mark bundle as not supporting multiuse

< HTTP/1.1 400
< Vary: Origin
< Vary: Access-Control-Request-Method
< Vary: Access-Control-Request-Headers
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 0
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< Pragma: no-cache
< Expires: 0
< X-Frame-Options: DENY
< Content-Length: 0
< Date: Sun, 22 Jun 2025 17:17:59 GMT
< Connection: close

getStudentsByNameAndCourseName_existingStudent
> GET /api/v1/students/name=Sergey/course=Python HTTP/1.1
> Host: localhost:8080
> User-Agent: insomnia/11.1.0
> Accept: */*

* Mark bundle as not supporting multiuse

< HTTP/1.1 200
< Vary: Origin
< Vary: Access-Control-Request-Method
< Vary: Access-Control-Request-Headers
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 0
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< Pragma: no-cache
< Expires: 0
< X-Frame-Options: DENY
< Content-Type: application/json
< Transfer-Encoding: chunked
< Date: Sun, 22 Jun 2025 17:19:53 GMT
[
	{
		"id": 4,
		"patronymic": null,
		"email": "s_sergeev@mail.ru",
		"reviews": [],
		"firstName": "Sergey",
		"lastName": "Sergeev",
		"birthDate": "2000-10-10",
		"coursesNames": [
			"JavaEE",
			"Python"
		]
	}
]

getStudentsByNameAndCourseName_notExistingStudent
> GET /api/v1/students/name=Sergey/course=Scala HTTP/1.1
> Host: localhost:8080
> User-Agent: insomnia/11.1.0
> Accept: */*

* Mark bundle as not supporting multiuse

< HTTP/1.1 200
< Vary: Origin
< Vary: Access-Control-Request-Method
< Vary: Access-Control-Request-Headers
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 0
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< Pragma: no-cache
< Expires: 0
< X-Frame-Options: DENY
< Content-Type: application/json
< Transfer-Encoding: chunked
< Date: Sun, 22 Jun 2025 17:21:16 GMT
[]

getStudentsByCourseCount=2
> GET /api/v1/students/course-count=2 HTTP/1.1
> Host: localhost:8080
> User-Agent: insomnia/11.1.0
> Accept: */*

* Mark bundle as not supporting multiuse

< HTTP/1.1 200
< Vary: Origin
< Vary: Access-Control-Request-Method
< Vary: Access-Control-Request-Headers
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 0
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< Pragma: no-cache
< Expires: 0
< X-Frame-Options: DENY
< Content-Type: application/json
< Transfer-Encoding: chunked
< Date: Sun, 22 Jun 2025 17:22:29 GMT
[
	{
		"id": 4,
		"patronymic": null,
		"email": "s_sergeev@mail.ru",
		"reviews": [],
		"firstName": "Sergey",
		"lastName": "Sergeev",
		"birthDate": "2000-10-10",
		"coursesNames": [
			"JavaEE",
			"Python"
		]
	},
	{
		"id": 6,
		"patronymic": "Ivanovich",
		"email": "alex@mail.ru",
		"reviews": [
			{
				"text": "{\n\t\"review\": \"Good course!\"\n}",
				"courseName": "Python"
			},
			{
				"text": "{\n\t\"review\": \"Good course!\"\n}",
				"courseName": "JavaEE"
			}
		],
		"firstName": "Alex",
		"lastName": "Ivanov",
		"birthDate": "1990-06-22",
		"coursesNames": [
			"JavaEE",
			"Python"
		]
	}
]

getStudentsByCourseCount=5
> GET /api/v1/students/course-count=5 HTTP/1.1
> Host: localhost:8080
> User-Agent: insomnia/11.1.0
> Accept: */*

* Mark bundle as not supporting multiuse

< HTTP/1.1 200
< Vary: Origin
< Vary: Access-Control-Request-Method
< Vary: Access-Control-Request-Headers
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 0
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< Pragma: no-cache
< Expires: 0
< X-Frame-Options: DENY
< Content-Type: application/json
< Transfer-Encoding: chunked
< Date: Sun, 22 Jun 2025 17:23:41 GMT
[]